# Generated by Django 4.2 on 2023-07-01 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0012_product_shopitem_review_productimage'),
        ('Like', '0012_userinfo'),
    ]

    operations = [
    ]
