# Generated by Django 4.2 on 2023-07-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Like', '0013_merge_20230701_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
